#!/usr/bin/env bash

## Set functions
display_help () {
	if (( Code == 0 )); then
		printf "${Genie} %s\n" \
			"This is The Great Brewdini. He grants one specific wish:"
		printf "%s\n\n" \
			"${cPrp}${cBld}   \"Update all Homebrew Formulae & Casks in a single command!\"${cOff}"
	fi
	printf '%s\n%s\n' "Usage:" \
		"   ${cBld}brewdini [-option] [--option]${cOff}"
	printf '\n%s\n%s\n%s\n%s\n'  "Options: " \
		"   ${cBld}-h, --help${cOff}   Displays help & usage" \
		"   ${cBld}-f, --force${cOff}  Force-upgrade Formulae & Casks marked as 'latest'" \
		"   ${cBld}-c, --check${cOff}  Runs 'brew doctor' after updates complete to check Homebrew"
	exit $Code
}

wrong_dir () {
	printf "\a${Genie} %s\n" \
		"${cPrp}WARNING: Homebrew not found in default location: '${cOff}$(brew --prefix)${cPrp}'"
	printf '%s\n\n%s\n' \
		"This is problematic and should be corrected before checking for updates." \
		"Visit the following URL for more information:${cOff}"
	printf '%s\n' \
		"${cBld}https://docs.brew.sh/FAQ#why-should-i-install-Homebrew-in-the-default-location${cOff}"
	printf '\n%s\n' \
		"${cPrp}No wishes granted; exiting.${cOff}"
	exit 1
}

## Set variables
Genie="\U1F9DE"		# 🧞
cBld=$(tput bold)
cPrp=$(tput setaf 103)
cOff=$(tput sgr0)
Args=(--quiet --yes)
ScriptDir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
Thunk=$ScriptDir/back-into-the-bottle.mp3

## Parse command line options
unset Code Doctor
while true; do
	shopt -s nocasematch
	case "$1" in
		-f | --force )
			Args+=(--greedy)
			shift
		;;
		-c | --check )
			Doctor=y
			shift
		;;
		-h | --help )
			Code=0
			display_help
		;;
		\?)
		;;
		"" )
			shift
			break
		;;
		* )
			printf "\a${Genie} %s\n%s\n\n" \
				"${cPrp}Sorry, The Great Brewdini cannot grant that wish..." \
				"   '$*' is an unknown option.${cOff}"
			Code=1
			display_help
		;;
	esac
done

## Test for Apple silicon
if [[ $(arch) == arm64 ]]; then
	if [[ $(brew --prefix) != /opt/homebrew ]]; then
		wrong_dir
	fi
else
	if [[ $(brew --prefix) != /usr/local ]]; then
		wrong_dir
	fi
fi

## Check for Homebrew, Formulae, and Cask upgrades; install them all
printf "${Genie} %s\n" \
	"${cPrp}Checking Homebrew & Formulae for updates...${cOff}"
if [[ $(brew update) != "Already up-to-date." ]]; then
	printf "\n${Genie} %s\n" \
		"${cPrp}Granting wish; upgrading Homebrew & Formulae...${cOff}"
	brew upgrade "${Args[@]}"
fi

## Clean Homebrew
printf "\n${Genie} %s\n" \
	"${cPrp}Cleaning up Formulae...${cOff}"
brew cleanup --prune=all

## Wish Granted!
printf "\n${Genie} %s\n" \
	"${cPrp}Your wish has been granted! Update process is complete!${cOff}"
if [[ -z $Doctor ]]; then
	afplay "$Thunk" >/dev/null 2>&1 & true
	exit 0
fi

## Check Homebrew
printf '%s\n' \
	"   Now checking Homebrew...${cOff}"

## Exit normally if OK
if brew doctor; then
	printf "%s ${Genie}\n" \
		"${cPrp}Done!${cOff}"
		afplay "$Thunk" >/dev/null 2>&1 & true
	exit 0
else
	## Exit abormally with message if not OK
	printf "\a${Genie} %s\n" \
		"${cPrp}Exiting with abnormal status; see above messaging.${cOff}"
		afplay "$Thunk" >/dev/null 2>&1 & true
	exit 1
fi
